server:
  port: 8091

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:8092/eureka/
  server:
    enable-self-preservation: false