CREATE TABLE `sys_log` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(255) NOT NULL COMMENT '用户名',
  `OPERATION` varchar(255) DEFAULT NULL COMMENT '用户操作',
  `TIME` int(11) NOT NULL COMMENT '响应时长',
  `METHOD` varchar(200) NOT NULL COMMENT '请求方法',
  `PARAMS` varchar(255) NOT NULL COMMENT '请求参数',
  `IP` varchar(255) NOT NULL DEFAULT '127.0.0.1' COMMENT 'IP地址',
  `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='日志记录';

