server:
  port: 9991

spring:
  application:
    name: Server-Provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8091/eureka/,http://peer2:8092/eureka/
